--- 
services: 
  infracloudio: 
    image: infracloudio/csvserver
    ports: 
      - "9393:9300"
    volumes: 
      - "/root/csvserver/solution/inputFile:/csvserver/inputdata"
    environment: 
      - CSVSERVER_BORDER=Orange
version: "3"

